name: rag_1

path:
  docs: "docs"
  export_extracted: "${.docs}/extracted/${..name}"
  database: "database/${..name}"

vision_llm:
  _target_: langchain_openai.AzureChatOpenAI
  azure_endpoint: ${oc.env:VISION_OPENAI_ENDPOINT}
  openai_api_key: ${oc.env:VISION_OPENAI_API_KEY}
  openai_api_version: "2024-02-15-preview"
  deployment_name: "gpt-4-vision"
  temperature: 0.0
  max_tokens: 1024

embedding:
  _target_: langchain_experimental.open_clip.OpenCLIPEmbeddings
  model_name: "ViT-H-14"
  checkpoint: "laion2b_s32b_b79k"

vectorstore:
  _target_: langchain_community.vectorstores.Chroma
  collection_name: "clip_photos"
  embedding_function: ${..embedding}
  persist_directory: "${..path.database}/chroma_db"

retriever:
  _target_: langchain_core.vectorstores.VectorStoreRetriever
  vectorstore: ${..vectorstore}
  search_type: "similarity"

ingest:
  chunking_enable: True
  chunking_func:
    _target_: unstructured.chunking.title.chunk_by_title
    _partial_: True
    max_characters: 4000
    new_after_n_chars: 3800
    combine_text_under_n_chars: 2000

  table_format: "html" # "text" or "html" or "image"

  export_extracted: True

  metadata_keys:
    - filename
    - page_number
